import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <Toaster richColors />
        <div className="min-h-screen flex flex-col">
          <div className="border-b py-4">
            <div className="container flex justify-center gap-6">
              <Link href={"/"}>
                <h1 className=" flex justify-center text-lg font-bold ">
                  <span>100<span className="text-red-700">x</span>Devs Web-based wallet </span>
                  
                </h1>
              </Link>
              
            </div>
          </div>
          <main className="flex-1">{children}</main>
          
        </div>
      </body>
    </html>
  );
}
